sudo: false
language: go

go:
  - 1.7

os:
  - linux
  - osx

install:
  - go get github.com/elastic/beats/libbeat
  - go get github.com/garyburd/redigo/redis
  - go get github.com/stretchr/testify/assert

script: make testsuite

after_success:
  - test -f build/coverage/full.cov && bash <(curl -s https://codecov.io/bash) -f build/coverage/full.cov
